version: "3.9"

services:

  php:
    build:
      context: ./php/
      dockerfile: PHP.Dockerfile
      args:
        - PHP_SUFIX=${PHP_SUFIX}
        - PHP_VERSION=${PHP_VERSION}
        - WORKDIR=${APP_CODE_PATH_CONTAINER}
        - PRJ_NAME=${PRJ_NAME}
    container_name: php
    expose:
      - "9000" # Expose port for PHP-FPM
