version: '3.8'

services:
  php:
    image: sammy266/mm-bk-php:latest
    container_name: php
    expose:
      - "9000" # Expose port for PHP-FPM
    depends_on:
      - mysql
    networks:
      - app-network
    # ...other settings

  nginx:
    image: sammy266/mm-bk-nginx:latest
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80" # for web ui
      - "88:88" # for web api
      - "${NGINX_HOST_HTTPS_PORT}:443"
    container_name: nginx
    networks:
      - app-network
    depends_on:
      - php
      - mysql
    # ...other settings

  mysql:
    image: sammy266/mm-bk-mysql:latest
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql
    networks:
      - app-network
    # ...other settings
networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}
